# FROM: Benauca
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-keycloak-pv-volume
  labels:
    type: local
    app: pg-keycloak
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-keycloak-pv-claim
  labels:
    app: pg-keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
