apiVersion: v1
kind: Service
metadata:
  namespace: bbcron-dev
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8180
      targetPort: 8180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: bbcron-dev
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        env:         
         - name: DB_ADDR
           value: postgres
         - name: DB_DATABASE
           value: keycloak_bb
         - name: DB_PASSWORD
           value: bbcron
         - name: DB_USER
           value: bbcron
         - name: DB_VENDOR
           value: POSTGRES
         - name: KEYCLOAK_PASSWORD
           value: bbcron
         - name: KEYCLOAK_USER
           value: bbcron
         - name: KEYCLOAK_VERSION
           value: 12.0.4        
         - name: KEYCLOAK_LOGLEVEL
           value: INFO
         - name: PROXY_ADDRESS_FORWARDING
           value: "true"
        image: mihaibob/keycloak:12.0.4
        ports:
        - name: http
          containerPort: 8180
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realm/master
            port: 8180
          initialDelaySeconds: 30
          timeoutSeconds: 3
